def main():
	try:
		raise Exception("blah")
	except Exception:
		print("CAUGHT")
